### ISSUE TITLE
Error while Evaluation

### ISSUE THREAD

**Issue by shuntos** [bethgelab/siamese-mask-rcnn#10]
ValueError: Dimension 3 in both shapes must be equal, but are 512 and 1024. Shapes are [7,7,384,512] and [7,7,384,1024]. for 'Assign_3992' (op: 'Assign') with input shapes: [7,7,384,512], [7,7,384,1024].

**Comment by michaelisc** [comment]
Could you provide a bit more context, in which step you encounter this problem and if you changed anything in the model?

**Comment by michaelisc** [comment]
My guess would be, that you used the ```evaluation.ipynb``` notebook to evaluate the models which are provided in the ```experiments``` folder. Please use the ```experiments/evaluate-experiments.ipynb``` notebook for these models.

Explanation:
The config used in the ```evaluation.ipynb``` notebook is intended to evaluate a smaller model (```small_siamese_mrcnn_0160.h5```) which can be trained on one 12GB GPU. The models we use for our experiments (```large_siamese_mrcnn_*_*.h5```) are bigger and need 4 GPUs to train (but only 1 to evaluate). 
One difference between the small and large models is, that we increased the size of the fully connected layers in the classifier head from 512 to 1024 features. Your error seems to come from the fact, that you specified that your model should have 512 features while the model in the checkpoint has 1024 features (or the other way around).
