### ISSUE TITLE
Should the RPN_ANCHOR_SCALE in config,py be modified as the input size is only 512

### ISSUE THREAD

**Issue by zb1439** [bethgelab/siamese-mask-rcnn#11]
I noticed that this implementation is using 512 as the query image size. However, the max rpn anchor scale is set to be 512 by default. Should this be modified according to the input size?

**Comment by michaelisc** [comment]
We have models with two different input sizes in this repository. The ```train.ipynb``` model with 512px size and the models in ```experiments``` which have the default input size of 1024px. The latter are the more relevant models and thus the config.py should stay the same. However the config in the small models config should be changed. Thanks for catching this mistake!

**Comment by michaelisc** [comment]
I just saw, that we set the default input size to 512px in the ```config.py```. I think we should clean this up to make it less confusing for everyone. So thanks again for the catch!
