### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by trungpham2606** [bethgelab/siamese-mask-rcnn#16]
@michaelisc Hello michael, Iam trying to run training part in your work. But Iam having this error
![image](https://user-images.githubusercontent.com/35657426/63236091-9ee87d00-c266-11e9-9241-e85be50131ef.png)

I had verified that the number of workers is 0 and I also set the multiprocessing = False as well. But I still had that problem. 
Can you show me how to cope with that ?

**Comment by michaelisc** [comment]
This seems to be an error with keras and your hard-/software. I have no ide, how to fix this but maybe you can find some help in the issues of the [original matterport mask r-cnn](https://github.com/matterport/Mask_RCNN) or [keras](https://github.com/keras-team/keras).
