### ISSUE TITLE
plz help

### ISSUE THREAD

**Issue by kidcad1412** [bethgelab/siamese-mask-rcnn#20]
when I run _evaluate.ipynb_ it throw this error

`ValueError: Error when checking : expected input_target to have shape (5, 96, 96, 3) but got array with shape (1, 96, 96, 3)
`

**Comment by michaelisc** [comment]
Sorry, I somehow missed this. Can you quickly state, what caused the error and how you fixed it?

**Comment by kidcad1412** [comment]
oh&nbsp; it's my mistake.I forgot change the number of classes.
sorry to bother you.


 
---Original---

**Comment by li-yanling** [comment]
> oh&nbsp; it's my mistake.I forgot change the number of classes. sorry to bother you.
> […](#)
> ---Original--- From: "Claudio Michaelis"<notifications@github.com&gt; Date: Wed, Oct 16, 2019 16:19 PM To: "bethgelab/siamese-mask-rcnn"<siamese-mask-rcnn@noreply.github.com&gt;; Cc: "State change"<state_change@noreply.github.com&gt;;"kidcad1412"<603944787@qq.com&gt;; Subject: Re: [bethgelab/siamese-mask-rcnn] plz help (#20) Sorry, I somehow missed this. Can you quickly state, what caused the error and how you fixed it? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi, same error happens to me. Could you give some suggestion? Thanks.

**Comment by ddddyyyy** [comment]
> > oh  it's my mistake.I forgot change the number of classes. sorry to bother you.
> > […](#)
> > ---Original--- From: "Claudio Michaelis"<[notifications@github.com](mailto:notifications@github.com)> Date: Wed, Oct 16, 2019 16:19 PM To: "bethgelab/siamese-mask-rcnn"<[siamese-mask-rcnn@noreply.github.com](mailto:siamese-mask-rcnn@noreply.github.com)>; Cc: "State change"<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>;"kidcad1412"<[603944787@qq.com](mailto:603944787@qq.com)>; Subject: Re: [bethgelab/siamese-mask-rcnn] plz help (#20) Sorry, I somehow missed this. Can you quickly state, what caused the error and how you fixed it? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Hi, same error happens to me. Could you give some suggestion? Thanks.

In chapter of "Visualization" ,modify config.NUM_TARGETS to 1

**Comment by kidcad1412** [comment]
> > oh  it's my mistake.I forgot change the number of classes. sorry to bother you.
> > […](#)
> > ---Original--- From: "Claudio Michaelis"<[notifications@github.com](mailto:notifications@github.com)> Date: Wed, Oct 16, 2019 16:19 PM To: "bethgelab/siamese-mask-rcnn"<[siamese-mask-rcnn@noreply.github.com](mailto:siamese-mask-rcnn@noreply.github.com)>; Cc: "State change"<[state_change@noreply.github.com](mailto:state_change@noreply.github.com)>;"kidcad1412"<[603944787@qq.com](mailto:603944787@qq.com)>; Subject: Re: [bethgelab/siamese-mask-rcnn] plz help (#20) Sorry, I somehow missed this. Can you quickly state, what caused the error and how you fixed it? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Hi, same error happens to me. Could you give some suggestion? Thanks.

sorry，I missed your question. if you only have one class to detect，you should change the class number to 1.
