### ISSUE TITLE
shape error

### ISSUE THREAD

**Issue by andrew-jeremy** [bethgelab/siamese-mask-rcnn#21]
I am not able to go beyond the following error even though I have created a conda environment and installed all the required packages as required:
-->ValueError: Dimension 3 in both shapes must be equal, but are 512 and 1024. Shapes are [7,7,384,512] and [7,7,384,1024]. for 'Assign_362' (op: 'Assign') with input shapes: [7,7,384,512], [7,7,384,1024].

**Comment by michaelisc** [comment]
Hi, could you specify where in the code you encounter this error?
