### ISSUE TITLE
How to design the loss function？

### ISSUE THREAD

**Issue by kidcad1412** [bethgelab/siamese-mask-rcnn#23]
I confuse the loss function,please help.

**Comment by michaelisc** [comment]
I am not sure I understood your question. Are you asking, what the loss is composed of?

**Comment by kidcad1412** [comment]
I mean the loss function  is same as the loss function in Mask R-CNN ? How the metric show in the loss function?

**Comment by michaelisc** [comment]
Exactly. The only difference is that the classification is only done for 2 classes ("is this an object from the same category as the reference or is it background") and not 81 classes ("is this an object from one of 80 predefined categories or is it background"). We thus made no changes to the loss but only to the labels which are conditioned on the reference.

**Comment by kidcad1412** [comment]
thank you so much
