### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hashmymind** [bethgelab/siamese-mask-rcnn#25]
in the `evaluate.ipynb`,  `checkpoints/large_siamese_mrcnn_coco_full_0320.h` was missing a `5`  in the end 
```py
# Select checkpoint
if model_size == 'small':
    checkpoint = 'checkpoints/small_siamese_mrcnn_0160.h5'
elif model_size == 'large':
    checkpoint = 'checkpoints/large_siamese_mrcnn_coco_full_0320.h'
```

**Comment by michaelisc** [comment]
Thanks! I fixed this ([7f2ebf1](https://github.com/bethgelab/siamese-mask-rcnn/commit/7f2ebf17f98dd1dc09915aa764a077cbf4687718)).
