### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by abexultan** [bethgelab/siamese-mask-rcnn#26]
In `lib/model.py` at line 377:
```python
target_rois = KL.Lambda(lambda x: modellig.norm_boxes_graph(
                    x, K.shape(input_image)[1:3]))(input_rois)
```
`modellig` is supposed to be `modellib`

**Comment by michaelisc** [comment]
Thanks for pointing this out! Fixed in https://github.com/bethgelab/siamese-mask-rcnn/commit/49e7048da293b2fdfbaf55e8ee3717fecc0d61dd
