### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by DL-Alva** [bethgelab/siamese-mask-rcnn#3]
When I try to run train.ipynb on my server, it prompts out of memory and stops running when epochs is up to 40. The memory on my server is about 11G. How can I deal with it to run this program on my server successfully?

**Comment by michaelisc** [comment]
Do you mean 11G of GPU memory or RAM?

As the training is set up in the train.ipynb it starts training deeper layers from epoch 40 onwards. This is why it requires more memory from that point on. If you want to reduce memory consumption you should reduce the batch size and scale the learning rate appropriately:
```
new_lr = old_lr * (new_batch_size/old_batch_size)
```
So if you half the batch size you should also halve the learning rate.

**Comment by michaelisc** [comment]
Oh. And I found a small bug. The training should be done on the complete network and not the heads alone from the second epoch on. I just fixed this, so for the correct schedule please pull the repo again. 

Also: if you want to reach the sampe performance we do in the paper please use the training notebooks from the experiments folder. If you don't have 4 GPUs just reduce that number to 1 and reduce the learning rate accordingly ```new_lr = old_lr\4```. I never tried it but this should give you the same results we got. As the network is bigger and the images larger it will however also take longer to train.

**Comment by DL-Alva** [comment]
Thank you very much for your answer. I will run the code again according to your suggestion.

**Comment by DL-Alva** [comment]
![GitHub](https://user-images.githubusercontent.com/22760056/55770657-b4c78380-5ab7-11e9-9bb8-6545897528c5.png)

I rerun the code you fixed. However it still prompts out of memory and need to allocating 1.87GiB while 3GiB more at the last time. Should I reduce the learning rate again？

**Comment by michaelisc** [comment]
Yes. You should try to further reduce the batch size and learning rate. Probably try 
``` 
GPU_COUNT = 1
IMAGES_PER_GPU = 6
LEARNING_RATE = 0.01
```
So you have a batch size of 6 and halved the learning rate. 
If that works you can try to increase the batch_size again.

**Comment by DL-Alva** [comment]
Thank you for your reply and I will try again according to your suggestion. But it seems that the batch size in the origin code is 1 and couldn't be reduced.

**Comment by michaelisc** [comment]
The default batch size is set to 1 in ```lib/config.py``` but it is overwritten in the ```TrainConfig``` sub-class defined in the ```train.ipynb``` notebook.

**Comment by DL-Alva** [comment]
I got it! Thank you for your reminder.
