### ISSUE TITLE
PRE_NMS_LIMIT

### ISSUE THREAD

**Issue by yuriyOn** [bethgelab/siamese-mask-rcnn#4]
I got an error while running first evaluate.ipynb and then train.ipynb that PRE_NMS_LIMIT is not defined in the model.py. I have found in the original Mask R-CNN implementation that it should be set to 6000. You should add the parameter to avoid the error to both files.

**Comment by michaelisc** [comment]
It seems you are using a more recent version of the Matterport Mask R-CNN than included in the repo. The PRE_NMS_LIMIT was fixed to 6000 back then. Can you test if any other things fail with the newer version of Mask R-CNN? If this is the only thing we have to change I am happy to add this.

**Comment by yuriyOn** [comment]
Another problem is listed in issue #1 and it is solved by replacing the Mask_RCNN directory with the latest version.

**Comment by michaelisc** [comment]
The problem with PRE_NMS_LIMIT should be fixed with commit 2a677a9eab5d023f06f088a1e99d7c3e2d008eb9. Now the settings from the original ```Config``` class from ```Mask_RCNN/mrcnn/config.py``` are inherited.

**Comment by michaelisc** [comment]
However we should still update the Mask_RCNN repository at some point.

**Comment by michaelisc** [comment]
We should still update ```lib/Mask_RCNN```. See issue #5
