### ISSUE TITLE
Understanding about "NUM_CLASSES" and  "IMAGE_META_SIZE" in config.py

### ISSUE THREAD

**Issue by DL-Alva** [bethgelab/siamese-mask-rcnn#7]
I‘m sorry to bother you again.  I can't grasp the meaning of "NUM_CLASSES" especially it‘s set to "1 + 1" in  train.ipynb or initialized as "1" in config.py. Besides, I can make sense of the computation of "IMAGE_META_SIZE " in "self.IMAGE_META_SIZE = 1 + 3 + 3 + 4 + 1 + self.NUM_CLASSES".

**Comment by michaelisc** [comment]
The number of classes is 1 foreground class + 1 background class. For normal coco training it would be 80 foreground classes and 1 background class. This value is superscribed in ```train.ipynb``` in the definition of the ```TrainConfig``` class. 
Image meta contains various pieces of information about the model setup. Especially an active class info was parsed withing the last n values. We don't use this feature but rather handle active classes in the data loading process.

**Comment by DL-Alva** [comment]
The train_classes is set in this way "train_classes = np.array(range(1,81))" in train.ipynb. What is the difference between the usage of "train_classes" and "NUM_CLASSES"?

**Comment by michaelisc** [comment]
- ```NUM_CLASSES``` is a parameter of the model, defining how many outputs the classifier has.
- ```train_classes``` specifies, which of the 80 classes in coco to use for training. In the ```experiments``` notebooks which have held-out classes for one-shot evaluation, this is not an array from 1 to 80 but a subset of this array containing only 60 classes, whose annotations are subsequently used during training.

**Comment by DL-Alva** [comment]
A subset of train_classes acts as the query categories whose annotations are used in the training process. Could I understand in this way?

**Comment by michaelisc** [comment]
Yes. Exactly. ```train_classes``` specifies this subset.

**Comment by discretecoder** [comment]
I have 25 instance classes and 50 total classes. when i set number of classes to 25+1, it is throwing an error but it works with num_classses 51.  
has anyone faced this kind of an issue

**Comment by michaelisc** [comment]
What kind of model are you training? Can it be, that your class indices are in [1,50] and thus any class indexed by a number in [25,50] is problematic? If this is your problem you should make sure to change the class index if the instance classes so that all of them are in [1,25].
