### ISSUE TITLE
How are samples of imagenet preprocessed during pretraining?

### ISSUE THREAD

**Issue by zb1439** [bethgelab/siamese-mask-rcnn#9]
Just wondering how is the pretrained images preprocessed, are they scaled to be 0-1 and normalized with imagenet mean and std?

**Comment by michaelisc** [comment]
We use the same preprocessing during pretraining as during training. Images are therefore only centered around zero by subtracting the coco mean but not scaled. The corresponding function is ```mold_image``` in ```lib/Mask_RCNN/mrcnn/model.py```.

**Comment by zb1439** [comment]
Thanks a lot!! Really appreciate your quick response!

**Comment by michaelisc** [comment]
Happy that I was able to help!
